remote_theme: mmistakes/minimal-mistakes@4.26.2
title: Open Source Strategy
logo: assets/images/RTE_LogoSeul_RVB.png
copyright_text: RTE France. Unless otherwise indicated, content is licensed under
copyright: CC-BY-4.0.
copyright_url: https://creativecommons.org/licenses/by/4.0/
breadcrumbs: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  projects_lfe:
    output: true
    permalink: /:path/
  projects_rte:
    output: true
    permalink: /:path/
  projects_contribution:
    output: true
    permalink: /:path/

include:
  - _pages
  - _projects_lfe
  - _projects_rte
  - _projects_contribution

#tag_archive:
#  type: liquid
#  path: /tags/

minimal_mistakes_skin: rte

github:
  is_project_page: false
  show_downloads: false
  owner_name: RTE France
  owner_url: https://www.rte-france.com

atom_feed:
  hide: true

twitter:
  username: rte_france

footer:
  links:
    - icon: "fab fa-fw fa-square-x-twitter"
      url: https://twitter.com/rte_france
    - icon: "fab fa-fw fa-youtube-square"
      url: https://www.youtube.com/user/myRTEtube
    - icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/company/rte_245681
    - icon: "fab fa-fw fa-square-instagram"
      url: https://www.instagram.com/rte_france
