theme: jekyll-theme-slate
title: RTE France
description:

github:
  is_project_page: false
  show_downloads: false
  owner_name: RTE France
  owner_url: https://www.rte-france.com

hades2:
  release: 6.6.0
  version: 6.6.0.1
  integration_version: 2.14.0
